### PR TITLE
Add colour icons, and convert to 25x25.

### PR DESCRIPTION
**Pull request by bwinton**
as per the [migration guide](https://developer.pebble.com/guides/migration/migration-guide-4/#launcher-icon)

It now looks like this in the launcher:
pebble_screenshot_2016-08-30_21-58-47

and this in the splash screen:
pebble_screenshot_2016-08-30_22-00-27

### CODE REVIEW

**Comment by chesterbr** [comment]
Oh, those are cute - great job! 🌈

**Comment by chesterbr** [comment]
Ah, I wanted to notice that, but my emulator is busted. Anyway, I tested on a Pebble Classic (aplite), and got the background issue with the PR (before the last commit):

pebble_pr_-_carlos_nascimento_shopify_com_-_shopify_mail

whereas the original app fills it in nicely:

img_20160831_084056

Pebble Round (Chalk) seemed to work fine.

Does the last commit also change it for Aplite? (I can test it later)

**Comment by bwinton** [comment]
It didn't, but I tried changing it back to `"bitmap"`.  Can you let me know if that fixes it?
(I can't seem to get to the menu in the aplite emulator, but this latest version looks fine on basalt, chalk, and diorite…)

**Comment by chesterbr** [comment]
Still the same result :-(

I remember making this work required changing the bitmap to a 1-bit pallet (done [here](https://github.com/chesterbr/toronto-transit-time/commit/1326c0539ff04615b201fea104e57bab26fa863e) for the old icon) *and* adding the `"memoryFormat": "1Bit"` and (counter-intuitively) the `"type": "bitmap",` ([here](https://github.com/chesterbr/toronto-transit-time/commit/5aa605ca708be0ad7a3e1c0e722e7e05fe8dc398)). I just don't remember how I did the conversion...

**Comment by chesterbr** [comment]
Just to illustrate, in your branch:
```bash
$ file resources/img/streetcar2525.png
resources/img/streetcar2525.png: PNG image data, 25 x 25, 8-bit/color RGB, non-interlaced
```
whereas the original was:

```bash
$ file resources/img/streetcar2828.png
resources/img/streetcar2828.png: PNG image data, 28 x 28, 1-bit colormap, non-interlaced
```

**Comment by chesterbr** [comment]
But mind you, I've just added the `"memoryFormat": "1Bit"` back and the transparency worked, even with the 8-bit file, so I guess that would be the solution)

(that said, ImageMagick does the conversion if you ask *really* nicely:
```bash
$ convert resources/img/streetcar2525.png -background white -type palette -depth 1 -colors 2 output.png
$ file output.png
output.png: PNG image data, 25 x 25, 1-bit grayscale, non-interlaced
```
)

**Comment by chesterbr** [comment]
I've added that parameter (doesn't seem to affect colour displays) and merged, will complete with credits and publish soon. Thanks again!

**Pull request merged**
